
package com.vista;

import com.dao.DaoCliente;
import com.modelo.Cliente;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author felix
 */
public class FrmCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCliente
     */
    public FrmCliente() {
        initComponents();
        tablaA();
    }
    
    Cliente cliente = new Cliente();
    DaoCliente daoc = new DaoCliente();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jNumeroDocumento = new javax.swing.JTextField();
        jDireccion = new javax.swing.JTextField();
        jIDDepartamento = new javax.swing.JTextField();
        jNacionalidad = new javax.swing.JTextField();
        jCorreoCliente = new javax.swing.JTextField();
        jTelefonoCliente = new javax.swing.JTextField();
        jApellidoCliente = new javax.swing.JTextField();
        jNombreCliente = new javax.swing.JTextField();
        jICliente = new javax.swing.JTextField();
        jTipoDocumento = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaCliente = new javax.swing.JTable();
        jBtnAgregar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jBtnActualizar = new javax.swing.JButton();
        jLimpiar = new javax.swing.JButton();
        jGenero = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Cliente");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ID Cliente");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Apellido");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Genero");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Telefono");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Correo");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Nacionalidad");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Tipo de Documento");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Numero de Documento");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Direccion");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("ID Departamento");

        jCorreoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCorreoClienteActionPerformed(evt);
            }
        });

        jApellidoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jApellidoClienteActionPerformed(evt);
            }
        });

        jNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNombreClienteActionPerformed(evt);
            }
        });

        jICliente.setEditable(false);
        jICliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIClienteActionPerformed(evt);
            }
        });

        jTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DUI", "Pasaporte", "Carnet Menoridad" }));

        jTablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablaCliente);

        jBtnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/save.png"))); // NOI18N
        jBtnAgregar.setText("Agregar");
        jBtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAgregarMouseClicked(evt);
            }
        });

        jbtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/x-button.png"))); // NOI18N
        jbtnEliminar.setText("Eliminar");
        jbtnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnEliminarMouseClicked(evt);
            }
        });

        jBtnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rotate.png"))); // NOI18N
        jBtnActualizar.setText("Modificar");
        jBtnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnActualizarMouseClicked(evt);
            }
        });

        jLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/brush.png"))); // NOI18N
        jLimpiar.setText("Limpiar");
        jLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLimpiarMouseClicked(evt);
            }
        });

        jGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jICliente)
                                .addComponent(jNombreCliente)
                                .addComponent(jApellidoCliente)
                                .addComponent(jTelefonoCliente)
                                .addComponent(jGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jIDDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 55, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtnAgregar)
                .addGap(18, 18, 18)
                .addComponent(jBtnActualizar)
                .addGap(18, 18, 18)
                .addComponent(jbtnEliminar)
                .addGap(18, 18, 18)
                .addComponent(jLimpiar)
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jICliente)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addComponent(jDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jIDDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(96, 96, 96))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAgregar)
                    .addComponent(jbtnEliminar)
                    .addComponent(jLimpiar)
                    .addComponent(jBtnActualizar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jApellidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jApellidoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jApellidoClienteActionPerformed

    private void jNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNombreClienteActionPerformed

    private void jIClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIClienteActionPerformed

    private void jCorreoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCorreoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCorreoClienteActionPerformed

    private void jBtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAgregarMouseClicked
        //********************////
         try
        {
           insertar();
           limpiar();
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
         tablaA();
    }//GEN-LAST:event_jBtnAgregarMouseClicked

    private void jTablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaClienteMouseClicked
         llenarTabla();
    }//GEN-LAST:event_jTablaClienteMouseClicked

    private void jbtnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnEliminarMouseClicked
        eliminar();
    }//GEN-LAST:event_jbtnEliminarMouseClicked

    private void jBtnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnActualizarMouseClicked
        modificar();
    }//GEN-LAST:event_jBtnActualizarMouseClicked

    private void jLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLimpiarMouseClicked
        limpiar();
    }//GEN-LAST:event_jLimpiarMouseClicked

     public void llenarTabla()
    {
        int fila = this.jTablaCliente.getSelectedRow();
        this.jICliente.setText(String.valueOf(this.jTablaCliente.getValueAt(fila, 0)));
        this.jNombreCliente.setText(String.valueOf(this.jTablaCliente.getValueAt(fila, 1)));
        this.jApellidoCliente.setText(String.valueOf(this.jTablaCliente.getValueAt(fila, 2)));
        this.jGenero.setSelectedItem(String.valueOf(this.jTablaCliente.getValueAt(fila, 3)));
        this.jTelefonoCliente.setText(String.valueOf(this.jTablaCliente.getValueAt(fila, 4)));
        this.jCorreoCliente.setText(String.valueOf(this.jTablaCliente.getValueAt(fila, 5)));
        this.jNacionalidad.setText(String.valueOf(this.jTablaCliente.getValueAt(fila, 6)));
        this.jTipoDocumento.setSelectedItem(String.valueOf(this.jTablaCliente.getValueAt(fila, 7)));
        this.jNumeroDocumento.setText(String.valueOf(this.jTablaCliente.getValueAt(fila, 8)));
        this.jDireccion.setText(String.valueOf(this.jTablaCliente.getValueAt(fila, 9)));
        this.jIDDepartamento.setText(String.valueOf(this.jTablaCliente.getValueAt(fila, 10)));
    }
     
     public void insertar() throws Exception
    {
        cliente.setId_cliente(PROPERTIES);
        cliente.setNombres(this.jNombreCliente.getText());
        cliente.setApellidos(this.jApellidoCliente.getText());
        cliente.setGenero(this.jGenero.getSelectedItem().toString());
        cliente.setTelefono(Integer.parseInt(this.jTelefonoCliente.getText()));
        cliente.setCorreo(this.jCorreoCliente.getText());
        cliente.setNacionalidad(this.jNacionalidad.getText());
        cliente.setTipo_documento(this.jTipoDocumento.getSelectedItem().toString());
        cliente.setNum_documento(Integer.parseInt(this.jNumeroDocumento.getText()));
        cliente.setDireccion(this.jDireccion.getText());
        cliente.setId_departamento(Integer.parseInt(this.jIDDepartamento.getText()));
        daoc.insertarCliente(cliente);
        JOptionPane.showMessageDialog(null, "Datos insertados con exito", "Insertando Datos", 3);
        daoc.mostrarCliente(); 
    }
     
     public void limpiar()
    {
        this.jICliente.setText("");
        this.jNombreCliente.setText("");
        this.jApellidoCliente.setText("");
        this.jTelefonoCliente.setText("");
        this.jCorreoCliente.setText("");
        this.jNacionalidad.setText("");
        this.jNumeroDocumento.setText("");
        this.jDireccion.setText("");
        this.jIDDepartamento.setText("");
    }
    
     public void modificar()
    {
        try
        {
            cliente.setId_cliente(Integer.parseInt(this.jICliente.getText()));
            cliente.setNombres(this.jNombreCliente.getText());
            cliente.setApellidos(this.jApellidoCliente.getText());
            cliente.setGenero(this.jGenero.getSelectedItem().toString());
            cliente.setTelefono(Integer.parseInt(this.jTelefonoCliente.getText()));
            cliente.setCorreo(this.jCorreoCliente.getText());
            cliente.setNacionalidad(this.jNacionalidad.getText());
            cliente.setTipo_documento(this.jTipoDocumento.getSelectedItem().toString());
            cliente.setNum_documento(Integer.parseInt(this.jNumeroDocumento.getText()));
            cliente.setDireccion(this.jDireccion.getText());
            cliente.setId_departamento(Integer.parseInt(this.jIDDepartamento.getText()));
            int sn = JOptionPane.showConfirmDialog(rootPane, "Usuario Modificado con Exito", "Modificar Usuario", JOptionPane.YES_NO_OPTION);
            if(sn ==0)
            {
              daoc.modificarCliente(cliente);
              JOptionPane.showMessageDialog(rootPane, "El usuario ha sido actualizado", "Confirmando", JOptionPane.INFORMATION_MESSAGE);
              tablaA();
              limpiar();
            }
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }
    
    public void eliminar()
    {
        try 
        {
            cliente.setId_cliente(Integer.parseInt(this.jICliente.getText()));
            int sn = JOptionPane.showConfirmDialog(rootPane, "Desea Eliminar el usuario?", "Eliminando Usuario", JOptionPane.YES_NO_OPTION);
            if(sn == 0)
            {
               daoc.eliminarCliente(cliente);
               JOptionPane.showMessageDialog(rootPane, "Eliminando con exito", "Confirmacion", JOptionPane.INFORMATION_MESSAGE);
               tablaA();
               limpiar();
            }
            else
            {
                limpiar();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e.toString(), "Error en el try-catch de la funcion eliminar", JOptionPane.ERROR_MESSAGE);
        }
    }
    
      public void tablaA()
    {
        String[] col = {"ID","Nombre","Apellido","Genero", "Telefono", "correo", "Nacionalidad","Tipo documento", "Numero Documento","Direccion","ID Departamento"};
        Object[] obj = new Object[11];
        DefaultTableModel tabla = new DefaultTableModel(null, col);
        List ls;
        try
        {
            ls = daoc.mostrarCliente();
            for(int i = 0; i < ls.size(); i++)
            {
                cliente = (Cliente) ls.get(i);
                obj[0] = cliente.getId_cliente();
                obj[1] = cliente.getNombres();
                obj[2] = cliente.getApellidos();
                obj[3] = cliente.getGenero();
                obj[4] = cliente.getTelefono();
                obj[5] = cliente.getCorreo();
                obj[6] = cliente.getNacionalidad();
                obj[7] = cliente.getTipo_documento();
                obj[8] = cliente.getNum_documento();
                obj[9] = cliente.getDireccion();
                obj[10] = cliente.getId_departamento();
                tabla.addRow(obj);
            }
            ls = daoc.mostrarCliente();
            this.jTablaCliente.setModel(tabla);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error al mostrar los datos... " + e.toString());
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField jApellidoCliente;
    private javax.swing.JButton jBtnActualizar;
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JTextField jCorreoCliente;
    private javax.swing.JTextField jDireccion;
    private javax.swing.JComboBox<String> jGenero;
    private javax.swing.JTextField jICliente;
    private javax.swing.JTextField jIDDepartamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLimpiar;
    private javax.swing.JTextField jNacionalidad;
    private javax.swing.JTextField jNombreCliente;
    private javax.swing.JTextField jNumeroDocumento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaCliente;
    private javax.swing.JTextField jTelefonoCliente;
    private javax.swing.JComboBox<String> jTipoDocumento;
    private javax.swing.JButton jbtnEliminar;
    // End of variables declaration//GEN-END:variables
}
